### ISSUE TITLE
contract code size exceeds 24576

### ISSUE THREAD

**Issue by Topian-1238** [lacchain/sol-falcon-verify#21]
hi , i am facing issues in deployment of this contract, i have tried on remix and truffle but even after enabling optimisation code is too ling to be deployed.

kindly can you guide me, how to resolve this issue

**Comment by eum602** [comment]
Hi @Topian-1238 what happens is the size is way higher than the maximum permitted amount, this is why it is not possible to deploy it on mainnet. You can for sure deploy it on development networks. [Here](https://github.com/eum602/simple-besu-eth-cient/tree/falcon-512) (make sure to be on branch _falcon-512_) I have a network configuration that you can try,  just clone the repo, go to branch `falcon-512` and then run `docker-compose up` which will start a development network with a higher block gas limit enough to have the contract deployed. After that you can go and run the soidity falcon tests with ` npx hardhat test test/falcon-512-test.js --network development`

Hope this helps

**Comment by eum602** [comment]
closing this since previous comment addresses the question
